Services:
  app:
    build: ./appp
    env_file: '.env'
    ports:
      -"8501:8501"
    depends_on:
      -llm
    
  llm:
    provider:
      type: model
      options:
        model: ${LLM_MODEL_NAME:-ai/gemma3}